/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Datum"][];
                        "application/json": components["schemas"]["Datum"][];
                        "text/json": components["schemas"]["Datum"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/HistoricalData/{dataId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dataId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HistoricalDatum"][];
                        "application/json": components["schemas"]["HistoricalDatum"][];
                        "text/json": components["schemas"]["HistoricalDatum"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/DataStadistic/{dataId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dataId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DataStadistic"];
                        "application/json": components["schemas"]["DataStadistic"];
                        "text/json": components["schemas"]["DataStadistic"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/DataRelation/{dataIdSource}/{dataIdTarget}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dataIdSource: number;
                    dataIdTarget: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DataRelation"];
                        "application/json": components["schemas"]["DataRelation"];
                        "text/json": components["schemas"]["DataRelation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Datum: {
            /** Format: int32 */
            dataId?: number;
            dataName?: string | null;
            /** Format: int32 */
            sourceId?: number;
            sourceAccess?: string | null;
            isValue?: boolean;
            historicalData?: components["schemas"]["HistoricalDatum"][] | null;
            source?: components["schemas"]["Source"];
        };
        HistoricalDatum: {
            /** Format: int64 */
            historicalDataId?: number;
            /** Format: date */
            date?: string;
            /** Format: int32 */
            dataId?: number;
            /** Format: float */
            value?: number;
            data?: components["schemas"]["Datum"];
        };
        DataStadistic: {
            /** Format: int32 */
            dataId?: number;
            /** Format: float */
            cagr?: number;
            /** Format: float */
            volatilidadcruda?: number;
            /** Format: float */
            volatilidaddetendenciada?: number;
            /** Format: float */
            sortino?: number;
            /** Format: float */
            sharpe?: number;
        };
        DataRelation: {
            /** Format: int32 */
            dataIdSource?: number;
            /** Format: int32 */
            dataIdTarget?: number;
            /** Format: int32 */
            dataRelationId?: number;
            /** Format: float */
            correlation?: number;
            /** Format: float */
            covariance?: number;
            /** Format: float */
            correlationLog?: number;
        };
        Source: {
            /** Format: int32 */
            sourceId?: number;
            sourceName?: string | null;
            data?: components["schemas"]["Datum"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
